# Generated by Django 4.0.4 on 2022-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hitpoints', models.IntegerField()),
                ('gold', models.DecimalField(decimal_places=4, max_digits=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
