# Generated by Django 4.0.4 on 2022-05-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_hero_mana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='mana',
        ),
    ]
