# Generated by Django 4.0.4 on 2022-05-26 10:57

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_hero_mana'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='mana',
            field=models.IntegerField(default=myapi.models.getRandomMana),
        ),
    ]
